# Generated by Django 4.2 on 2025-08-22 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kriteria', models.CharField(max_length=200)),
                ('bobot', models.FloatField()),
                ('tipe_kriteria', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pelanggan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pelanggan', models.CharField(max_length=200)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pesanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pesan', models.DateField()),
                ('jumlah_galon', models.IntegerField()),
                ('tanggal_pengiriman', models.DateField()),
                ('pelanggan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pelanggan')),
            ],
        ),
        migrations.CreateModel(
            name='Pengiriman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_kirim', models.DateField()),
                ('status_pengiriman', models.CharField(max_length=50)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pesanan')),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kriteria')),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pesanan')),
            ],
        ),
    ]
