# Generated by Django 5.2.3 on 2025-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesanan',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
